FROM opensuse/leap:16.0

ENV version=v4
ARG bashrc=https://raw.githubusercontent.com/analogdevicesinc/doctools/refs/heads/ci/bashrc
ARG entrypoint_sh=https://raw.githubusercontent.com/analogdevicesinc/doctools/refs/heads/ci/entrypoint.sh
ARG git_defaults_sh=https://raw.githubusercontent.com/analogdevicesinc/doctools/refs/heads/ci/git-defaults.sh
ARG gh_actions_runner_sh=https://raw.githubusercontent.com/analogdevicesinc/doctools/refs/heads/ci/gh-actions-runner.sh

RUN zypper update -y
RUN zypper install -y --no-recommends \
    tar unzip gzip curl jq libicu coreutils  update-alternatives

RUN useradd -m runner
WORKDIR /home/runner

ENV FORCE_JAVASCRIPT_ACTIONS_TO_NODE24=true
ADD ${gh_actions_runner_sh} .
RUN bash ./gh-actions-runner.sh ; rm ./gh-actions-runner.sh

# Install packages required by Buildroot:
# https://buildroot.org/downloads/manual/manual.html#requirement-mandatory
RUN zypper install -y --no-recommends gcc gcc-c++ make glibc-devel glibc-gconv-modules-extra \
    libstdc++-devel binutils ccache git wget rsync bc unzip cpio file which \
    sed diffutils bash patch gzip bzip2 perl tar findutils gawk ncurses-devel zlib-devel

# For utils/generate-cyclonedx
RUN zypper install -y --no-recommends \
    python313
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.13 313

RUN mkdir -p /usr/local/bin
WORKDIR /usr/local/bin
ADD ${entrypoint_sh} .
RUN chmod +rx ./entrypoint.sh

ADD ${git_defaults_sh} .
RUN bash ./git-defaults.sh ; rm ./git-defaults.sh

USER runner
WORKDIR /home/runner
RUN curl -o .bashrc -L ${bashrc} ; \
    chmod +x .bashrc

ENTRYPOINT ["/bin/bash"]
