name: Build ADI artifacts

on:
  workflow_dispatch:
    inputs:
      defconfig:
        description: Buildroot defconfig
        required: true
        type: string
      flavor:
        description: Configuration flavor
        required: false
        type: string
        default: ''
  workflow_call:
    inputs:
      defconfig:
        required: true
        type: string
      flavor:
        required: false
        type: string
        default: ''

jobs:
  build:
    runs-on: ${{ vars.RUNNER != '' && fromJSON(vars.RUNNER) || 'ubuntu-latest' }}
    permissions:
      contents: write

    steps:
      - name: Checkout br2-external
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Build image
        run: |
          cd buildroot
          umask 022
          make distclean
          make BR2_EXTERNAL="${PWD}/.." ${{ inputs.defconfig }}
          support/kconfig/merge_config.sh .config \
            "../configs/buildroot.fragment"
          if [ -n "${{ inputs.flavor }}" ]; then
            support/kconfig/merge_config.sh .config \
              "../configs/${{ inputs.flavor }}.fragment"
          fi
          make -j$(nproc)

      - name: Build SDK
        if: ${{ github.event_name == 'release' || github.event_name == 'workflow_dispatch' }}
        run: |
          cd buildroot
          make sdk -j$(nproc)

      - name: Generate SBOM
        run: |
          [[ "${{ runner.debug }}" == "1" ]] && set -x
          image_path="buildroot/output/images"

          defconfig="${{ inputs.defconfig }}"
          [ -n "${{ inputs.flavor }}" ] && defconfig="${defconfig}-${{ inputs.flavor }}"

          # buildroot >= 2024.05
          cd buildroot
          make show-info \
            | utils/generate-cyclonedx \
                --project-name "$defconfig" \
                --project-version "${{ github.ref_name }}" \
            > "../${image_path}/sbom.json"

      - name: Prepare image names
        run: |
          image_name="${{ inputs.defconfig }}"
          [ -z "${{ inputs.flavor }}" ] || image_name="${image_name}-${{ inputs.flavor }}"
          echo "image_name=$image_name" >> "$GITHUB_ENV"

      - name: Upload Buildroot images
        uses: actions/upload-artifact@v6
        with:
          name: ${{ env.image_name }}
          path: buildroot/output/images

