name: Build aarch64 Fedora root filesystem

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write

jobs:
  build-rootfs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Install mkosi
        run: pipx install git+https://github.com/systemd/mkosi.git

      - name: Install host dependencies
        run: |
          sudo apt-get update -q
          sudo apt-get install -y dnf rpm bubblewrap

      - name: Build rootfs
        run: sudo -E $(which mkosi) -C ci build

      - name: Upload rootfs
        uses: actions/upload-artifact@v6
        with:
          name: adsp-arm64-rootfs
          path: ci/mkosi.output/adsp-arm64-rootfs.tar.zst
          retention-days: 30
