name: Build and Hardware Test

on:
  workflow_dispatch:
   inputs:
     skip-hw-test:
       description: "Skip hardware tests"
       default: false
       type: boolean
  pull_request:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build-buildroot:
    strategy:
      fail-fast: false
      matrix:
        include:
          - defconfig: adi_sc598_ezkit_defconfig
            flavor: debug
          - defconfig: adi_sc598_ezkit_defconfig
            flavor: bootstrap
          - defconfig: adi_sc598_ezlite_defconfig
            flavor: debug
          - defconfig: adi_sc598_ezlite_defconfig
            flavor: bootstrap
          - defconfig: adi_sc846_ezkit_defconfig
            flavor: debug
          - defconfig: adi_sc846_ezkit_defconfig
            flavor: bootstrap
          - defconfig: zynq_pluto_defconfig
          - defconfig: zynq_m2k_defconfig
          - defconfig: microblaze_adi_rootfs_defconfig
    uses: ./.github/workflows/build.yml
    with:
      defconfig: ${{ matrix.defconfig }}
      flavor: ${{ matrix.flavor }}
    permissions:
      contents: write

  build-mkosi-fedora:
    uses: ./.github/workflows/fedora.yml
    permissions:
      contents: write

  bundle:
    needs: [build-buildroot, build-mkosi-fedora]
    strategy:
      matrix:
        include:
          - defconfig: adi_sc598_ezkit_defconfig
            rootfs: adsp-arm64-rootfs
          - defconfig: adi_sc598_ezlite_defconfig
            rootfs: adsp-arm64-rootfs
          - defconfig: adi_sc846_ezkit_defconfig
            rootfs: adsp-arm64-rootfs
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download bootstrap artifact
        uses: actions/download-artifact@v8
        with:
          name: ${{ matrix.defconfig }}-bootstrap
          path: images/bootstrap

      - name: Download debug artifact
        uses: actions/download-artifact@v8
        with:
          name: ${{ matrix.defconfig }}-debug
          path: images/debug

      - name: Download rootfs artifact
        uses: actions/download-artifact@v8
        with:
          name: ${{ matrix.rootfs }}
          path: images/fedora

      - name: Upload bundle artifact
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.defconfig }}
          path: images

      - name: Archive bundle
        if: ${{ github.event_name == 'release' }}
        run: |
          bundle_name="${{ matrix.defconfig }}-${{ github.event.release.tag_name }}"
          mv images "$bundle_name"
          tar -cJf "${bundle_name}.tar.xz" "$bundle_name"
          echo "bundle_archive=${bundle_name}.tar.xz" >> "$GITHUB_ENV"

      - name: Upload bundle to release
        if: ${{ github.event_name == 'release' }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.bundle_archive }}
          tag: ${{ github.ref }}
          overwrite: true

  hardware-test:
    needs: [bundle]
    if: ${{ !inputs.skip-hw-test && github.event_name != 'release' }}
    strategy:
      fail-fast: false
      matrix:
        test-set: [adsp/u-boot, adsp/bootstrap, adsp/initramfs-boot]
        needs:
          - '["sc598", "ezkit"]'
          - '["sc598", "ezlite"]'
          - '["sc846", "ezkit"]'
    uses: analogdevicesinc/hw-test/.github/workflows/run-test.yml@main
    with:
      set: >-
        {"name":"${{ matrix.test-set }}","needs":${{ matrix.needs }}}
    secrets: inherit
    permissions:
      actions: read
      contents: read
      id-token: write

  deploy_cloudsmith:
    needs: [build-buildroot]
    if: ${{ github.event_name != 'release' && !cancelled() }}
    uses: analogdevicesinc/linux/.github/workflows/upload-to-cloudsmith.yml@ci
    secrets:
      CLOUDSMITH_SERVICE_SLUG: ${{ secrets.CLOUDSMITH_SERVICE_SLUG }}
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    permissions:
      id-token: write
      contents: read
      actions: read
    with:
      artifacts: >
        *_defconfig*
